import { createApp } from 'vue'
import './style.css'
//import App from './views/Title.vue'
//import App from './views/CreateAccount.vue'
//import App from './views/MainMenu.vue'
//import App from './views/Account.vue'
//import App from './views/Backpack.vue'
//import App from './views/Ranking.vue'
//import App from './views/OtherAccount.vue'
//import App from './views/StoreMenu.vue'
//import App from './views/CreateAttack.vue'
//import App from './views/SellAttack.vue'
//import App from './views/GameCreation.vue'
//import App from './views/Statistics.vue'
//import App from './views/BuyAttack.vue'
import App from './views/GameFinder.vue'
createApp(App).mount('#app')
